### ISSUE TITLE
运行后 访问 500

### ISSUE THREAD

**Issue by lewisLANG** [code-scan/LoginFish#1]
[GIN] 2022/06/29 - 09:43:27 | 404 |         990ns |  116.238.91.126 | GET      "/admin_index.html"

2022/06/29 09:43:46 /root/gotools/LoginFish-main/pkg/model/site.go:25 record not found
[0.408ms] [rows:0] SELECT * FROM `sites` WHERE Domain = "106.75.252.199"  AND `sites`.`deleted_at` IS NULL ORDER BY `sites`.`id` LIMIT 1
[GIN] 2022/06/29 - 09:43:46 | 500 |     590.828µs |  116.238.91.126 | GET      "/"
[GIN] 2022/06/29 - 09:45:49 | 404 |         1.5µs |  116.238.91.126 | GET      "/login"

**Comment by code-scan** [comment]
/admin/login 不是/login
