### ISSUE TITLE
Confuse[域名和具体的端口号是怎么定义的？]

### ISSUE THREAD

**Issue by huzai9527** [code-scan/LoginFish#2]
我如何能够访问到自定义的域名呢

**Comment by code-scan** [comment]
增加站点,在域名选项中写你自己的域名就可以了

然后把你指定的域名,比如说是`1.baidu.com`,解析到你执行LoginFish服务器所在的ip

端口看readme
`./LoginFish port`

把port改成你自己需要监听的端口就行了,比如说80

**Comment by huzai9527** [comment]
那1.baidu.com的端口号呢，解析我通过host改了，也能ping通，但是访问不行

**Comment by code-scan** [comment]
端口号就是启动的时候的端口

**Comment by chenqingbab** [comment]
我咋还是么东呢需要自己有一个域名解析到我的ip上吗
