### ISSUE TITLE
Feature[能否尝试获取更多用户信息]

### ISSUE THREAD

**Issue by huzai9527** [code-scan/LoginFish#5]
- 能够在攻击者不知情，或者不下载马的情况下获取攻击者信息
- 尝试通过在打开网页的时候，通过其他网站的一些漏洞，获取更多信息
- 如jsonp跨域、xss等获取常用网站的cookie等
- ref：https://www.freebuf.com/articles/web/320869.html

**Comment by code-scan** [comment]
你可以自定义模板,然后通过参考login.js中post方法,把你想要获取的数据通过他传递到后台进行展示

LoginFish 更多的就是充当一个框架/快捷WebServer的角色,更多的使用方法应该是通过自己定义模板去实现他

我能做的是增加一些数据接受的接口或后台展示的方式
